version: '3.8'

services:
  
  stock-analyzer:
  
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-analyzer
    restart: unless-stopped
    user: "0:0"
    ports:
      - "8502:8502"
    volumes:
      # 數據持久化
      - ./data:/app/data
      # 配置文件（如果需要自定義）
      - ./config.py:/app/config.py:ro
      # 日誌目錄
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_PORT=8502
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - TZ=Asia/Hong_Kong
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=utf-8
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8502/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - stock-analyzer-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.25'
    entrypoint: >
      sh -c "chmod -R 777 /app/data &&
             exec streamlit run run_streamlit.py --server.address=0.0.0.0 --server.port=8502 --server.headless=true --server.fileWatcherType=none --browser.gatherUsageStats=false"

networks:
  stock-analyzer-network:
    driver: bridge
